### ISSUE TITLE
Registries name problem

### ISSUE THREAD

**Issue by chandon** [DXI-Ltd/doctrine-extension-bundle#1]
In compiler for ReferencePass, you have 

```
private static $registries = array(
    'orm' => 'doctrine',
    'odm' => 'doctrine_mongodb'
);
```

This should be 

```
private static $registries = array(
    'entity' => 'doctrine',
    'document' => 'doctrine_mongodb'
);
```

or you'll have compatibility issues + a bug with the ReferenceManyEmbed (has it already looks for "document" and not "odm")

**Comment by dbojdo** [comment]
Introduced the RegistryTypes constants to avoid such typos.
